version: "3.9"

services:
  backend:
    build: ./backend
    container_name: scrim-backend
    environment:
      - DATABASE_URL=postgresql://scrimuser:scrimpass@db:5432/scrimdb
    depends_on:
      - db
    networks:
      - scrim-net

  frontend:
    build: ./frontend
    container_name: scrim-frontend
    ports:
      - "3000:3000"
    networks:
      - scrim-net

  db:
    image: postgres:15
    container_name: scrim-db
    environment:
      - POSTGRES_USER=scrimuser
      - POSTGRES_PASSWORD=scrimpass
      - POSTGRES_DB=scrimdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - scrim-net

  nginx:
    image: nginx:alpine
    container_name: scrim-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - scrim-net

volumes:
  db_data:

networks:
  scrim-net:
